document.addEventListener('DOMContentLoaded', () => {

    // Trigger welcome screen stagger fade-in on load
    setTimeout(() => {
        const welcomeOverlay = document.getElementById('welcome-overlay');
        if (welcomeOverlay) welcomeOverlay.classList.add('welcome-loaded');
    }, 100);

    // ==========================================================================
    // SUPABASE CONFIGURATION & SCHEMA GUIDANCE
    // ==========================================================================
    // Tabla compartida "rsvp"; cada evento se distingue por la columna event_slug.
    //
    // create table rsvp (
    //   id bigint generated by default as identity primary key,
    //   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    //   event_slug text,
    //   nombre text not null,
    //   numero text not null,
    //   confirmacion boolean not null default true,
    //   mensaje text
    // );
    // create policy "Permitir registro público" on rsvp for insert to anon with check (true);

    const SUPABASE_URL = 'https://pncvqukbnuqvwgowperf.supabase.co';
    const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuY3ZxdWtibnVxdndnb3dwZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NTg4MjUsImV4cCI6MjA5NjEzNDgyNX0.uZWqxvl2kd7Fq9pNAIDi86zWwa0TWhbj0OrSLAmRciE';
    const EVENT_SLUG = 'enrique-diana';

    const SUPABASE_CDN = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
    let supabaseClient = null;
    let supabaseLoading = null;

    function loadScript(src) {
        return new Promise((resolve, reject) => {
            const s = document.createElement('script');
            s.src = src;
            s.async = true;
            s.onload = resolve;
            s.onerror = () => reject(new Error('No se pudo cargar ' + src));
            document.head.appendChild(s);
        });
    }

    // Carga el SDK de Supabase solo cuando se necesita (al abrir/enviar el RSVP).
    function ensureSupabase() {
        if (supabaseClient) return Promise.resolve(supabaseClient);
        if (!supabaseLoading) {
            supabaseLoading = (async () => {
                if (typeof supabase === 'undefined') {
                    await loadScript(SUPABASE_CDN);
                }
                supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
                return supabaseClient;
            })();
        }
        return supabaseLoading;
    }

    // ==========================================================================
    // AUDIO PLAYER & ONBOARDING SYSTEM (WITH INTERACTIVE ENVELOPE)
    // ==========================================================================
    const AUDIO_SRC = 'song.mp3?v=1';

    const welcomeOverlay = document.getElementById('welcome-overlay');
    const bgMusic = document.getElementById('bg-music');
    const btnMusic = document.getElementById('btn-music');
    const audioSource = document.getElementById('audio-source');

    const envelope = document.getElementById('envelope');
    const waxSeal = document.getElementById('wax-seal');

    audioSource.src = AUDIO_SRC;
    bgMusic.load();
    bgMusic.volume = 0.5;

    // Click wax seal to open envelope and enter automatically
    if (waxSeal && envelope) {
        waxSeal.addEventListener('click', (e) => {
            e.stopPropagation();
            envelope.classList.add('open');
            // Hide hint
            const hint = document.querySelector('.envelope-hint');
            if (hint) {
                hint.style.opacity = '0';
                setTimeout(() => hint.remove(), 400);
            }
            // Start preloading Supabase SDK for RSVP
            ensureSupabase().catch(() => {});

            // Auto-enter invitation after opening animation (1.2s delay).
            // Music does NOT autoplay — guests start it from the "Nuestra Canción" section.
            setTimeout(() => {
                welcomeOverlay.classList.add('dismissed');
                initScrollReveal();
                initAmbientParticles(); // Initialize falling leaves canvas
            }, 1200);
        });
    }

    btnMusic.addEventListener('click', (e) => {
        e.stopPropagation();
        if (bgMusic.paused) {
            playMusic();
        } else {
            pauseMusic();
        }
    });

    function playMusic() {
        bgMusic.volume = 0;
        bgMusic.play().then(() => {
            btnMusic.classList.add('playing');
            // Smoothly fade in volume to 0.4
            let vol = 0;
            const interval = setInterval(() => {
                if (vol >= 0.4) {
                    clearInterval(interval);
                    bgMusic.volume = 0.4;
                } else {
                    vol += 0.05;
                    bgMusic.volume = vol;
                }
            }, 150);
        }).catch(err => {
            console.log('Audio playback failed: ', err);
        });
    }

    function pauseMusic() {
        bgMusic.pause();
        btnMusic.classList.remove('playing');
    }

    // ==========================================================================
    // AMBIENT FLOATING LEAVES & PETALS (CANVAS-BASED)
    // ==========================================================================
    function initAmbientParticles() {
        if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

        const canvas = document.createElement('canvas');
        canvas.id = 'ambient-canvas';
        canvas.style.position = 'fixed';
        canvas.style.top = '0';
        canvas.style.left = '0';
        canvas.style.width = '100vw';
        canvas.style.height = '100vh';
        canvas.style.pointerEvents = 'none';
        canvas.style.zIndex = '0'; // Behind everything
        document.body.appendChild(canvas);

        const ctx = canvas.getContext('2d');
        let width = canvas.width = window.innerWidth;
        let height = canvas.height = window.innerHeight;

        window.addEventListener('resize', () => {
            width = canvas.width = window.innerWidth;
            height = canvas.height = window.innerHeight;
        }, { passive: true });

        const particles = [];
        // Two colors: primary olive (#54582f) and blush rose (#DFBDB3)
        const colors = [
            { r: 84, g: 88, b: 47, opacity: 0.12, type: 'leaf' },
            { r: 223, g: 189, b: 179, opacity: 0.18, type: 'petal' }
        ];

        class Particle {
            constructor() {
                this.reset();
                this.y = Math.random() * height; // Start at random height initially
            }

            reset() {
                this.x = Math.random() * width;
                this.y = -20;
                this.size = Math.random() * 8 + 6;
                this.speedY = Math.random() * 0.6 + 0.4;
                this.speedX = Math.random() * 0.4 - 0.2;
                const baseColor = colors[Math.floor(Math.random() * colors.length)];
                this.r = baseColor.r;
                this.g = baseColor.g;
                this.b = baseColor.b;
                this.opacity = baseColor.opacity;
                this.type = baseColor.type;
                this.angle = Math.random() * Math.PI * 2;
                this.spinSpeed = Math.random() * 0.02 - 0.01;
            }

            update() {
                this.y += this.speedY;
                this.x += this.speedX + Math.sin(this.y * 0.01) * 0.15; // gentle wave drift
                this.angle += this.spinSpeed;

                if (this.y > height + 20 || this.x < -20 || this.x > width + 20) {
                    this.reset();
                }
            }

            draw() {
                ctx.save();
                ctx.translate(this.x, this.y);
                ctx.rotate(this.angle);
                ctx.fillStyle = `rgba(${this.r}, ${this.g}, ${this.b}, ${this.opacity})`;
                ctx.beginPath();
                if (this.type === 'leaf') {
                    // Draw a simple leaf shape (two quadratic curves)
                    ctx.moveTo(0, -this.size);
                    ctx.quadraticCurveTo(this.size * 0.6, 0, 0, this.size);
                    ctx.quadraticCurveTo(-this.size * 0.6, 0, 0, -this.size);
                } else {
                    // Draw a soft rounded flower petal shape
                    ctx.moveTo(0, 0);
                    ctx.arc(0, 0, this.size * 0.5, 0, Math.PI * 2);
                }
                ctx.fill();
                ctx.restore();
            }
        }

        const maxParticles = Math.min(25, Math.floor((width * height) / 40000));
        for (let i = 0; i < maxParticles; i++) {
            particles.push(new Particle());
        }

        function animate() {
            ctx.clearRect(0, 0, width, height);
            for (let i = 0; i < particles.length; i++) {
                particles[i].update();
                particles[i].draw();
            }
            requestAnimationFrame(animate);
        }

        animate();
    }

    // ==========================================================================
    // COUNTDOWN TIMER — Sábado 25 de Julio 2026, 4:00 PM (16:00:00)
    // ==========================================================================
    const weddingDate = new Date('July 25, 2026 16:00:00').getTime();

    const countdownTimer = setInterval(() => {
        const now = new Date().getTime();
        const distance = weddingDate - now;

        if (distance < 0) {
            clearInterval(countdownTimer);
            const cd = document.getElementById('countdown');
            if (cd) cd.innerHTML = "<div class='wedding-started'>¡Hoy es nuestro gran día!</div>";
            return;
        }

        const days = Math.floor(distance / (1000 * 60 * 60 * 24));
        const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        const seconds = Math.floor((distance % (1000 * 60)) / 1000);

        const daysEl = document.getElementById('days');
        const hoursEl = document.getElementById('hours');
        const minutesEl = document.getElementById('minutes');
        const secondsEl = document.getElementById('seconds');

        if (daysEl) daysEl.innerText = String(days).padStart(2, '0');
        if (hoursEl) hoursEl.innerText = String(hours).padStart(2, '0');
        if (minutesEl) minutesEl.innerText = String(minutes).padStart(2, '0');
        if (secondsEl) secondsEl.innerText = String(seconds).padStart(2, '0');
    }, 1000);

    // ==========================================================================
    // COPY TO CLIPBOARD (cuentas bancarias)
    // ==========================================================================
    const copyButtons = document.querySelectorAll('.btn-copy');
    copyButtons.forEach(button => {
        button.addEventListener('click', () => {
            const targetId = button.getAttribute('data-target');
            const targetElement = document.getElementById(targetId);
            if (!targetElement) return;
            const textToCopy = targetElement.innerText || targetElement.textContent;

            navigator.clipboard.writeText(textToCopy).then(() => {
                button.classList.add('copied');
                const tooltip = button.querySelector('.tooltip-copy');
                if (tooltip) tooltip.innerText = '¡Copiado!';
                setTimeout(() => {
                    button.classList.remove('copied');
                    if (tooltip) tooltip.innerText = 'Copiar';
                }, 1500);
            }).catch(err => console.error('Failed to copy: ', err));
        });
    });

    // ==========================================================================
    // INTERACTIVE RSVP MODAL
    // ==========================================================================
    const btnRsvp = document.getElementById('btn-rsvp');
    const rsvpModal = document.getElementById('rsvp-modal');
    const modalClose = document.getElementById('modal-close');
    const formRsvp = document.getElementById('form-rsvp');

    // Prevent a second submission once this device has confirmed
    const RSVP_KEY = 'ed_rsvp_done';
    function isRsvpDone() {
        try { return !!localStorage.getItem(RSVP_KEY); } catch (e) { return false; }
    }
    function applyConfirmedUI() {
        const main = document.getElementById('btn-rsvp');
        if (main) {
            const s = main.querySelector('span');
            if (s) s.textContent = 'ASISTENCIA CONFIRMADA';
            main.classList.add('is-confirmed');
        }
        const floating = document.getElementById('floating-rsvp-btn');
        if (floating) {
            floating.classList.remove('show');
            floating.style.display = 'none';
        }
    }
    function markRsvpDone() {
        try { localStorage.setItem(RSVP_KEY, '1'); } catch (e) {}
        applyConfirmedUI();
    }

    function openRsvpModal() {
        if (isRsvpDone()) {
            showToast('Ya registramos tu confirmación. ¡Gracias! 🤍');
            return;
        }
        rsvpModal.classList.add('show');
        document.body.style.overflow = 'hidden';
        document.getElementById('rsvp-name').focus();
        ensureSupabase().catch(() => {});
    }

    if (btnRsvp) btnRsvp.addEventListener('click', openRsvpModal);
    if (isRsvpDone()) applyConfirmedUI();

    modalClose.addEventListener('click', closeModal);
    rsvpModal.addEventListener('click', (e) => {
        if (e.target === rsvpModal) closeModal();
    });

    function closeModal() {
        rsvpModal.classList.remove('show');
        document.body.style.overflow = '';
    }

    const toastEl = document.getElementById('toast');
    let toastTimer = null;
    function showToast(message, isError = false, duration = 3600) {
        if (!toastEl) return;
        toastEl.textContent = message;
        toastEl.classList.toggle('error', isError);
        toastEl.classList.add('show');
        clearTimeout(toastTimer);
        toastTimer = setTimeout(() => toastEl.classList.remove('show'), duration);
    }

    formRsvp.addEventListener('submit', async (e) => {
        e.preventDefault();

        const name = document.getElementById('rsvp-name').value.trim();
        const phone = document.getElementById('rsvp-phone').value.trim();
        const message = document.getElementById('rsvp-message').value.trim();
        const statusEl = document.querySelector('input[name="rsvp-status"]:checked');
        const confirmacion = statusEl ? statusEl.value === 'Si' : true;

        closeModal();
        showToast('Guardando tu confirmación…', false, 8000);

        try {
            const client = await ensureSupabase();
            const { error } = await client
                .from('rsvp')
                .insert([
                    {
                        event_slug: EVENT_SLUG,
                        nombre: name,
                        numero: phone,
                        confirmacion: confirmacion,
                        mensaje: message
                    }
                ]);

            if (error) throw error;

            formRsvp.reset();
            markRsvpDone();
            showToast(confirmacion
                ? '¡Gracias! Te esperamos con mucho cariño. 🤍'
                : 'Gracias por avisarnos, te vamos a extrañar. 🤍');
        } catch (error) {
            console.error('Error al registrar RSVP en Supabase:', error);
            openRsvpModal();
            showToast('No se pudo guardar. Revisa tu conexión e inténtalo de nuevo.', true, 4500);
        }
    });

    // ==========================================================================
    // SCROLL REVEAL (Intersection Observer)
    // ==========================================================================
    function initScrollReveal() {
        const revealElements = document.querySelectorAll('.reveal');

        const revealObserver = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('active');
                    observer.unobserve(entry.target);
                }
            });
        }, {
            threshold: 0.1,
            rootMargin: '0px 0px -40px 0px'
        });

        revealElements.forEach(element => revealObserver.observe(element));

        const timelineItems = document.querySelectorAll('.program-item');
        timelineItems.forEach((item, index) => {
            item.style.setProperty('--stagger-delay', index % 4);
        });
    }

    // ==========================================================================
    // SCROLL PROGRESS INDICATOR (fallback if no scroll-driven animations)
    // ==========================================================================
    const scrollProgress = document.getElementById('scroll-progress');
    if (scrollProgress && !CSS.supports('animation-timeline', 'scroll()')) {
        let ticking = false;
        window.addEventListener('scroll', () => {
            if (!ticking) {
                window.requestAnimationFrame(() => {
                    const winScroll = document.body.scrollTop || document.documentElement.scrollTop;
                    const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
                    const scrolled = height > 0 ? (winScroll / height) : 0;
                    scrollProgress.style.transform = `scaleX(${scrolled})`;
                    ticking = false;
                });
                ticking = true;
            }
        }, { passive: true });
    }

    // Fallback: if user reloads mid-scroll, ensure reveals are observed
    if (window.scrollY > 100) {
        initScrollReveal();
    }

    // ==========================================================================
    // STICKY FLOATING RSVP BUTTON
    // ==========================================================================
    const floatingRsvpBtn = document.getElementById('floating-rsvp-btn');
    const rsvpSection = document.getElementById('rsvp');

    if (floatingRsvpBtn) {
        floatingRsvpBtn.addEventListener('click', openRsvpModal);

        window.addEventListener('scroll', () => {
            if (isRsvpDone()) { floatingRsvpBtn.classList.remove('show'); return; }
            const scrollPos = window.scrollY || document.documentElement.scrollTop;
            const rsvpTop = rsvpSection ? rsvpSection.getBoundingClientRect().top + window.scrollY : 10000;
            const triggerPos = 400;
            const hidePos = rsvpTop - window.innerHeight + 100;

            if (scrollPos > triggerPos && scrollPos < hidePos) {
                floatingRsvpBtn.classList.add('show');
            } else {
                floatingRsvpBtn.classList.remove('show');
            }
        }, { passive: true });
    }

    // ==========================================================================
    // INTERACTIVE CALENDAR DROPDOWN MENU
    // ==========================================================================
    const calendarTriggers = document.querySelectorAll('.btn-calendar-trigger');
    calendarTriggers.forEach(trigger => {
        trigger.addEventListener('click', (e) => {
            e.stopPropagation();
            const parent = trigger.parentElement;
            document.querySelectorAll('.calendar-dropdown').forEach(dropdown => {
                if (dropdown !== parent) {
                    dropdown.classList.remove('open');
                }
            });
            parent.classList.toggle('open');
        });
    });

    document.addEventListener('click', () => {
        document.querySelectorAll('.calendar-dropdown').forEach(dropdown => {
            dropdown.classList.remove('open');
        });
    });
});
