document.addEventListener('DOMContentLoaded', () => {

    // ==========================================================================
    // SUPABASE CONFIGURATION & STORAGE GUIDANCE
    // ==========================================================================
    // Reemplaza los placeholders con la URL y la Anon Key de tu proyecto Supabase.
    // 
    // PASOS EN SUPABASE PARA ESTA PÁGINA:
    // 
    // 1. Crear la Tabla 'photos':
    //    create table photos (
    //      id bigint generated by default as identity primary key,
    //      created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    //      event_slug text not null,
    //      uploader_name text not null,
    //      photo_url text not null
    //    );
    //    Habilita RLS en la tabla 'photos' y añade dos políticas públicas:
    //    - Permitir lecturas públicas (select para anon con check true)
    //    - Permitir inserciones públicas (insert para anon con check true)
    // 
    // 2. Crear el Bucket de Almacenamiento (Storage):
    //    - Ve a 'Storage' en tu panel de Supabase.
    //    - Crea un nuevo bucket llamado "photos".
    //    - IMPORTANTE: Haz el bucket "Public" (Público) para que cualquiera pueda acceder a los links directos.
    //    - Añade políticas al bucket 'photos' para permitir que usuarios anónimos puedan subir archivos (upload/insert).
    
    const SUPABASE_URL = 'https://pncvqukbnuqvwgowperf.supabase.co';
    const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuY3ZxdWtibnVxdndnb3dwZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NTg4MjUsImV4cCI6MjA5NjEzNDgyNX0.uZWqxvl2kd7Fq9pNAIDi86zWwa0TWhbj0OrSLAmRciE';
    const EVENT_SLUG = 'joao-vitalia';

    let supabaseClient = null;

    if (typeof supabase !== 'undefined' && SUPABASE_URL !== 'YOUR_SUPABASE_URL') {
        supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    }

    // ==========================================================================
    // DOM ELEMENTS
    // ==========================================================================
    const formUpload = document.getElementById('form-upload');
    const fileInput = document.getElementById('file-input');
    const dropZone = document.getElementById('drop-zone');
    const previewGrid = document.getElementById('preview-grid');
    const uploadProgress = document.getElementById('upload-progress');
    const uploadProgressBar = uploadProgress.querySelector('span');
    const submitBtn = document.getElementById('btn-submit-upload');
    const submitBtnSpan = submitBtn.querySelector('span');
    const toastEl = document.getElementById('toast');

    const galleryGrid = document.getElementById('gallery-grid');
    const galleryEmpty = document.getElementById('gallery-empty');

    const lightbox = document.getElementById('lightbox');
    const lightboxImg = document.getElementById('lightbox-img');
    const lightboxClose = document.getElementById('lightbox-close');
    const lightboxMeta = document.getElementById('lightbox-meta');

    const MAX_FILE_MB = 15;
    const DEFAULT_UPLOADER = 'Invitado'; // column is NOT NULL; no name field anymore

    // Each entry: { file, url (objectURL), el (thumb element) }
    let selectedFiles = [];

    // Fetch and display photos immediately
    loadGallery();

    // ==========================================================================
    // TOAST (replaces blocking alert popups)
    // ==========================================================================
    let toastTimer = null;
    function toast(message, isError = false, duration = 3200) {
        toastEl.textContent = message;
        toastEl.classList.toggle('error', isError);
        toastEl.classList.add('show');
        clearTimeout(toastTimer);
        toastTimer = setTimeout(() => toastEl.classList.remove('show'), duration);
    }

    // ==========================================================================
    // FILE SELECTION & MULTI PREVIEW
    // ==========================================================================
    function openPicker() { fileInput.click(); }

    dropZone.addEventListener('click', openPicker);
    dropZone.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); openPicker(); }
    });

    fileInput.addEventListener('change', () => {
        addFiles(fileInput.files);
        fileInput.value = ''; // allow re-selecting the same file later
    });

    ['dragenter', 'dragover'].forEach(evt =>
        dropZone.addEventListener(evt, (e) => {
            e.preventDefault();
            dropZone.classList.add('dragover');
        })
    );
    ['dragleave', 'dragend', 'drop'].forEach(evt =>
        dropZone.addEventListener(evt, (e) => {
            e.preventDefault();
            dropZone.classList.remove('dragover');
        })
    );
    dropZone.addEventListener('drop', (e) => {
        if (e.dataTransfer.files.length) addFiles(e.dataTransfer.files);
    });

    function addFiles(fileList) {
        let rejected = 0;
        let tooBig = 0;
        Array.from(fileList).forEach(file => {
            if (!file.type.startsWith('image/')) { rejected++; return; }
            if (file.size > MAX_FILE_MB * 1024 * 1024) { tooBig++; return; }
            const entry = { file, url: URL.createObjectURL(file), el: null };
            selectedFiles.push(entry);
            renderThumb(entry);
        });

        if (rejected) toast('Algunos archivos no son imágenes y se omitieron.', true);
        else if (tooBig) toast(`Algunas fotos superan ${MAX_FILE_MB}MB y se omitieron.`, true);
        updateSubmitState();
    }

    function renderThumb(entry) {
        const thumb = document.createElement('div');
        thumb.className = 'preview-thumb';
        thumb.innerHTML = `
            <img src="${entry.url}" alt="Foto seleccionada">
            <button type="button" class="thumb-remove" aria-label="Quitar foto">&times;</button>
        `;
        thumb.querySelector('.thumb-remove').addEventListener('click', (e) => {
            e.stopPropagation();
            removeFile(entry);
        });
        entry.el = thumb;
        previewGrid.appendChild(thumb);
    }

    function removeFile(entry) {
        URL.revokeObjectURL(entry.url);
        if (entry.el) entry.el.remove();
        selectedFiles = selectedFiles.filter(f => f !== entry);
        updateSubmitState();
    }

    function updateSubmitState() {
        const n = selectedFiles.length;
        submitBtn.disabled = n === 0;
        submitBtnSpan.innerText = n === 0
            ? 'COMPARTIR FOTOS'
            : (n === 1 ? 'COMPARTIR 1 FOTO' : `COMPARTIR ${n} FOTOS`);
    }

    // ==========================================================================
    // UPLOAD LOGIC (sequential, with progress + per-thumb state)
    // ==========================================================================
    formUpload.addEventListener('submit', async (e) => {
        e.preventDefault();

        const uploaderName = DEFAULT_UPLOADER;
        if (!selectedFiles.length) { toast('Elige al menos una foto.', true); return; }

        if (!supabaseClient) {
            toast('Subida no configurada (faltan las llaves de Supabase).', true, 4500);
            return;
        }

        const total = selectedFiles.length;
        submitBtn.disabled = true;
        uploadProgress.classList.add('show');
        uploadProgressBar.style.width = '0%';

        let done = 0;
        let failed = 0;

        // Work on a snapshot so removals during upload don't break iteration
        const queue = [...selectedFiles];
        for (const entry of queue) {
            entry.el && entry.el.classList.add('uploading');
            submitBtnSpan.innerText = `SUBIENDO ${done + failed + 1} DE ${total}…`;
            try {
                await uploadOne(entry.file, uploaderName);
                done++;
                if (entry.el) entry.el.classList.add('done');
            } catch (err) {
                console.error('Error uploading photo:', err);
                failed++;
                if (entry.el) entry.el.classList.remove('uploading');
            }
            uploadProgressBar.style.width = `${Math.round(((done + failed) / total) * 100)}%`;
        }

        // Clean up successfully uploaded thumbs
        selectedFiles.forEach(entry => URL.revokeObjectURL(entry.url));
        selectedFiles = [];
        previewGrid.innerHTML = '';

        setTimeout(() => {
            uploadProgress.classList.remove('show');
            uploadProgressBar.style.width = '0%';
        }, 600);
        updateSubmitState();

        if (failed === 0) {
            toast(total === 1 ? '¡Foto compartida con éxito! 🤍' : `¡${done} fotos compartidas con éxito! 🤍`);
        } else if (done === 0) {
            toast('No se pudo subir. Revisa tu conexión e inténtalo de nuevo.', true, 4500);
        } else {
            toast(`Se subieron ${done} de ${total}. Reintenta las que faltaron.`, true, 4500);
        }

        loadGallery();
    });

    async function uploadOne(file, uploaderName) {
        const fileExt = (file.name.split('.').pop() || 'jpg').toLowerCase();
        const uniqueFileName = `${EVENT_SLUG}/${Date.now()}_${Math.random().toString(36).substring(2, 9)}.${fileExt}`;

        const { error: uploadError } = await supabaseClient
            .storage.from('photos')
            .upload(uniqueFileName, file, { cacheControl: '3600', upsert: false });
        if (uploadError) throw uploadError;

        const { data: { publicUrl } } = supabaseClient
            .storage.from('photos')
            .getPublicUrl(uniqueFileName);

        const { error: dbError } = await supabaseClient
            .from('photos')
            .insert([{ event_slug: EVENT_SLUG, uploader_name: uploaderName, photo_url: publicUrl }]);
        if (dbError) throw dbError;
    }

    // ==========================================================================
    // GET GALLERY LOGIC
    // ==========================================================================
    
    async function loadGallery() {
        if (!supabaseClient) {
            showDummyGallery();
            return;
        }

        try {
            const { data: photos, error } = await supabaseClient
                .from('photos')
                .select('*')
                .eq('event_slug', EVENT_SLUG)
                .order('created_at', { ascending: false });

            if (error) throw error;

            renderGallery(photos);
        } catch (err) {
            console.error('Error loading gallery from Supabase:', err);
            showDummyGallery();
        }
    }

    function renderGallery(photos) {
        galleryGrid.innerHTML = '';
        
        if (!photos || photos.length === 0) {
            galleryEmpty.style.display = 'flex';
            return;
        }

        galleryEmpty.style.display = 'none';

        photos.forEach((photo, index) => {
            const name = (photo.uploader_name || '').trim();
            const showName = name && name.toLowerCase() !== 'invitado';
            const item = document.createElement('div');
            item.className = 'gallery-item';
            item.style.setProperty('--stagger-delay', index % 12);
            item.innerHTML = `
                <img src="${photo.photo_url}" alt="Foto compartida${showName ? ' por ' + name : ''}" loading="lazy">
                ${showName ? `<div class="gallery-meta">Por: ${name}</div>` : ''}
            `;

            // Open full lightbox view on click
            item.addEventListener('click', () => {
                openLightbox(photo.photo_url, showName ? name : '');
            });

            galleryGrid.appendChild(item);
            
            // Trigger animation in the next paint frame
            requestAnimationFrame(() => {
                item.classList.add('reveal-active');
            });
        });
    }

    // Showcase placeholder local items if Supabase is unconfigured (for demo purposes)
    function showDummyGallery() {
        galleryGrid.innerHTML = '';
        galleryEmpty.style.display = 'flex';
        
        // Check if technical note already added to avoid duplicates
        if (!document.getElementById('supabase-note')) {
            const technicalNote = document.createElement('p');
            technicalNote.id = 'supabase-note';
            technicalNote.className = 'sub-text';
            technicalNote.style.marginTop = 'var(--space-sm)';
            technicalNote.style.fontSize = '0.8rem';
            technicalNote.style.opacity = '0.7';
            technicalNote.innerText = '(Los momentos compartidos aparecerán aquí una vez configurado Supabase)';
            galleryEmpty.appendChild(technicalNote);
        }
    }

    // ==========================================================================
    // LIGHTBOX LOGIC
    // ==========================================================================
    
    function openLightbox(url, name) {
        lightboxImg.src = url;
        lightboxMeta.innerText = name ? `Foto capturada por ${name}` : '';
        lightbox.classList.add('show');
        document.body.style.overflow = 'hidden';
    }

    lightboxClose.addEventListener('click', closeLightbox);

    lightbox.addEventListener('click', (e) => {
        if (e.target === lightbox || e.target === lightboxClose) {
            closeLightbox();
        }
    });

    function closeLightbox() {
        lightbox.classList.remove('show');
        lightboxImg.src = '';
        document.body.style.overflow = '';
    }

    // ==========================================================================
    // SCROLL PROGRESS INDICATOR
    // ==========================================================================
    const scrollProgress = document.getElementById('scroll-progress');
    window.addEventListener('scroll', () => {
        const winScroll = document.body.scrollTop || document.documentElement.scrollTop;
        const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
        const scrolled = (winScroll / height) * 100;
        if (scrollProgress) {
            scrollProgress.style.width = scrolled + '%';
        }
    });

    // ==========================================================================
    // SCROLL REVEAL (Intersection Observer)
    // ==========================================================================
    function initScrollReveal() {
        const revealElements = document.querySelectorAll('.reveal');
        
        const revealObserver = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('active');
                    observer.unobserve(entry.target); // Trigger once
                }
            });
        }, {
            threshold: 0.05,
            rootMargin: '0px 0px -20px 0px'
        });

        revealElements.forEach(element => {
            revealObserver.observe(element);
        });
    }

    // Initialize reveals
    initScrollReveal();
});
