document.addEventListener('DOMContentLoaded', () => {
    
    // Trigger welcome screen stagger fade-in on load
    setTimeout(() => {
        const welcomeOverlay = document.getElementById('welcome-overlay');
        if (welcomeOverlay) welcomeOverlay.classList.add('welcome-loaded');
    }, 100);

    // ==========================================================================
    // SUPABASE CONFIGURATION & SCHEMA GUIDANCE
    // ==========================================================================
    // Reemplaza los placeholders con la URL y la Anon Key de tu proyecto Supabase.
    // 
    // Para crear la tabla correspondiente, ejecuta esta sentencia en el editor SQL
    // de tu panel de Supabase:
    // 
    // create table rsvp (
    //   id bigint generated by default as identity primary key,
    //   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    //   nombre text not null,
    //   numero text not null,
    //   confirmacion boolean not null default true,
    //   mensaje text
    // );
    // 
    // Recuerda activar RLS y añadir una política para que cualquiera pueda registrarse (insertar):
    // create policy "Permitir registro público" on rsvp for insert to anon with check (true);
    
    const SUPABASE_URL = 'https://pncvqukbnuqvwgowperf.supabase.co';
    const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuY3ZxdWtibnVxdndnb3dwZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NTg4MjUsImV4cCI6MjA5NjEzNDgyNX0.uZWqxvl2kd7Fq9pNAIDi86zWwa0TWhbj0OrSLAmRciE';
    
    const SUPABASE_CDN = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
    let supabaseClient = null;
    let supabaseLoading = null;

    function loadScript(src) {
        return new Promise((resolve, reject) => {
            const s = document.createElement('script');
            s.src = src;
            s.async = true;
            s.onload = resolve;
            s.onerror = () => reject(new Error('No se pudo cargar ' + src));
            document.head.appendChild(s);
        });
    }

    // Carga el SDK de Supabase solo cuando se necesita (al abrir/enviar el RSVP),
    // para no descargarlo en cada visita a la invitación.
    function ensureSupabase() {
        if (supabaseClient) return Promise.resolve(supabaseClient);
        if (!supabaseLoading) {
            supabaseLoading = (async () => {
                if (typeof supabase === 'undefined') {
                    await loadScript(SUPABASE_CDN);
                }
                supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
                return supabaseClient;
            })();
        }
        return supabaseLoading;
    }

    // ==========================================================================
    // AUDIO PLAYER & ONBOARDING SYSTEM
    // ==========================================================================
    
    // Default background audio URL (Royalty-free romantic acoustic wedding track)
    // To change to the original song "Is This Love - Bob Marley", replace this URL 
    // with your preferred hosting link or direct stream.
    const AUDIO_SRC = 'song.mp3?v=2';
    
    const welcomeOverlay = document.getElementById('welcome-overlay');
    const btnEnter = document.getElementById('btn-enter');
    const bgMusic = document.getElementById('bg-music');
    const audioPlayer = document.getElementById('audio-player');
    const btnMusic = document.getElementById('btn-music');
    const audioSource = document.getElementById('audio-source');

    // Initialize audio element source
    audioSource.src = AUDIO_SRC;
    bgMusic.load();
    bgMusic.volume = 0.5; // Set elegant background volume

    // Dismiss welcome screen and play music
    btnEnter.addEventListener('click', () => {
        welcomeOverlay.classList.add('dismissed');
        audioPlayer.classList.remove('hidden');
        
        playMusic();
        initScrollReveal();
    });

    // Toggle Music Playback
    btnMusic.addEventListener('click', (e) => {
        e.stopPropagation(); // Avoid triggering document-level interaction listeners
        if (bgMusic.paused) {
            playMusic();
        } else {
            pauseMusic();
        }
    });

    function playMusic() {
        bgMusic.play().then(() => {
            btnMusic.classList.add('playing');
        }).catch(err => {
            console.log('Audio playback failed: ', err);
        });
    }

    function pauseMusic() {
        bgMusic.pause();
        btnMusic.classList.remove('playing');
    }

    // Dynamic Autoplay & User Interaction Bindings
    function setupAutoplay() {
        // 1. Try to play immediately (often blocked by modern browsers until interaction)
        bgMusic.play().then(() => {
            btnMusic.classList.add('playing');
            audioPlayer.classList.remove('hidden');
        }).catch(() => {
            console.log("Autoplay blocked. Waiting for first user interaction to start audio.");
            
            // 2. Play on first interaction anywhere on the page
            const startAudioOnInteraction = () => {
                bgMusic.play().then(() => {
                    btnMusic.classList.add('playing');
                    audioPlayer.classList.remove('hidden');
                    cleanupListeners();
                }).catch(err => {
                    console.log("Interaction play failed: ", err);
                });
            };

            const cleanupListeners = () => {
                document.removeEventListener('click', startAudioOnInteraction);
                document.removeEventListener('touchstart', startAudioOnInteraction);
                document.removeEventListener('scroll', startAudioOnInteraction);
            };

            document.addEventListener('click', startAudioOnInteraction);
            document.addEventListener('touchstart', startAudioOnInteraction);
            document.addEventListener('scroll', startAudioOnInteraction);
        });
    }

    // Initialize Autoplay setup
    setupAutoplay();

    // ==========================================================================
    // COUNTDOWN TIMER
    // ==========================================================================
    
    // Wedding Date: Saturday, July 18, 2026 at 5:30 PM (17:30:00)
    const weddingDate = new Date('July 18, 2026 17:30:00').getTime();

    const countdownTimer = setInterval(() => {
        const now = new Date().getTime();
        const distance = weddingDate - now;

        if (distance < 0) {
            clearInterval(countdownTimer);
            document.getElementById('countdown').innerHTML = "<div class='wedding-started'>¡Hoy es nuestro gran día!</div>";
            return;
        }

        // Calculations for days, hours, minutes, and seconds
        const days = Math.floor(distance / (1000 * 60 * 60 * 24));
        const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        const seconds = Math.floor((distance % (1000 * 60)) / 1000);

        // Update DOM elements with double digits
        document.getElementById('days').innerText = String(days).padStart(2, '0');
        document.getElementById('hours').innerText = String(hours).padStart(2, '0');
        document.getElementById('minutes').innerText = String(minutes).padStart(2, '0');
        document.getElementById('seconds').innerText = String(seconds).padStart(2, '0');
    }, 1000);

    // ==========================================================================
    // CALENDAR INTEGRATIONS
    // ==========================================================================
    
    const btnCalendar = document.getElementById('btn-calendar');
    const calendarDropdown = document.getElementById('calendar-dropdown');
    
    // Toggle calendar dropdown
    btnCalendar.addEventListener('click', (e) => {
        e.stopPropagation();
        const expanded = btnCalendar.getAttribute('aria-expanded') === 'true';
        btnCalendar.setAttribute('aria-expanded', !expanded);
        calendarDropdown.classList.toggle('show');
    });

    // Close calendar dropdown when clicking outside
    document.addEventListener('click', () => {
        btnCalendar.setAttribute('aria-expanded', 'false');
        calendarDropdown.classList.remove('show');
    });

    // Google Calendar URL (Peru local time UTC-5 starts at 5:30 PM -> 17:30)
    // 2026-07-18 at 17:30 is 22:30 UTC. Ending at 03:00 on July 19 (08:00 UTC)
    const googleCalUrl = 'https://calendar.google.com/calendar/render?action=TEMPLATE' +
        '&text=' + encodeURIComponent('Boda de Vitalia & Joao') +
        '&dates=20260718T223000Z/20260719T080000Z' +
        '&details=' + encodeURIComponent('Con la bendición de Dios y nuestros padres los invitamos a compartir este día tan especial con nosotros.\n\nHorario:\n- 5:30 pm: Recepción\n- 6:00 pm: Ceremonia Civil\n- 8:00 pm: Cena') +
        '&location=' + encodeURIComponent('Boulevard Park Plaza G-H 43 A, Urbanización Miraflores Country Club, Piura, Perú');
    
    document.getElementById('link-google-cal').href = googleCalUrl;

    // Apple/iCal .ics File Generator
    document.getElementById('link-ical').addEventListener('click', (e) => {
        e.preventDefault();
        
        const icsContent = [
            'BEGIN:VCALENDAR',
            'VERSION:2.0',
            'PRODID:-//Vitalia y Joao//Wedding Invite//ES',
            'BEGIN:VEVENT',
            'UID:wedding-joao-vitalia-2026@jydsiempre',
            'DTSTAMP:20260604T120000Z',
            'DTSTART:20260718T173000', // Local time (standard format for float)
            'DTEND:20260719T033000',
            'SUMMARY:Boda Vitalia & Joao',
            'DESCRIPTION:Con la bendición de Dios y nuestros padres los invitamos a compartir este día con nosotros. Codigo Novios: 734956-04.',
            'LOCATION:Boulevard Park Plaza G-H 43 A\\, Urbanización Miraflores Country Club\\, Piura\\, Perú',
            'END:VEVENT',
            'END:VCALENDAR'
        ].join('\r\n');

        const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
        const link = document.createElement('a');
        link.href = window.URL.createObjectURL(blob);
        link.setAttribute('download', 'Boda_Vitalia_y_Joao.ics');
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    });

    // ==========================================================================
    // COPY TO CLIPBOARD
    // ==========================================================================
    
    const copyButtons = document.querySelectorAll('.btn-copy');

    copyButtons.forEach(button => {
        button.addEventListener('click', () => {
            const targetId = button.getAttribute('data-target');
            const targetElement = document.getElementById(targetId);
            
            if (!targetElement) return;

            const textToCopy = targetElement.innerText || targetElement.textContent;
            
            // Use Clipboard API
            navigator.clipboard.writeText(textToCopy).then(() => {
                // Show copied tooltip state
                button.classList.add('copied');
                const tooltip = button.querySelector('.tooltip-copy');
                if (tooltip) {
                    tooltip.innerText = '¡Copiado!';
                }
                
                // Revert tooltip after 1.5 seconds
                setTimeout(() => {
                    button.classList.remove('copied');
                    if (tooltip) {
                        tooltip.innerText = 'Copiar';
                    }
                }, 1500);
            }).catch(err => {
                console.error('Failed to copy: ', err);
            });
        });
    });

    // ==========================================================================
    // INTERACTIVE RSVP MODAL & WHATSAPP
    // ==========================================================================
    
    // RSVP Whatsapp phone number (Default placeholder, wedding planner or couple's phone)
    const btnRsvp = document.getElementById('btn-rsvp');
    const rsvpModal = document.getElementById('rsvp-modal');
    const modalClose = document.getElementById('modal-close');
    const formRsvp = document.getElementById('form-rsvp');

    // --- Prevent a second submission once this device has confirmed ---
    const RSVP_KEY = 'jv_rsvp_done';
    function isRsvpDone() {
        try { return !!localStorage.getItem(RSVP_KEY); } catch (e) { return false; }
    }
    function applyConfirmedUI() {
        const main = document.getElementById('btn-rsvp');
        if (main) {
            const s = main.querySelector('span');
            if (s) s.textContent = 'ASISTENCIA CONFIRMADA';
            main.classList.add('is-confirmed');
        }
        const floating = document.getElementById('floating-rsvp-btn');
        if (floating) {
            floating.classList.remove('show');
            floating.style.display = 'none';
        }
    }
    function markRsvpDone() {
        try { localStorage.setItem(RSVP_KEY, '1'); } catch (e) {}
        applyConfirmedUI();
    }

    // Open Modal
    function openRsvpModal() {
        if (isRsvpDone()) {
            showToast('Ya registramos tu confirmación. ¡Gracias! 🤍');
            return;
        }
        rsvpModal.classList.add('show');
        document.body.style.overflow = 'hidden'; // Stop background scrolling
        document.getElementById('rsvp-name').focus();
        ensureSupabase().catch(() => {}); // Precarga en segundo plano para un envío instantáneo
    }

    if (btnRsvp) {
        btnRsvp.addEventListener('click', openRsvpModal);
    }

    // Reflect a prior confirmation on load
    if (isRsvpDone()) applyConfirmedUI();

    // Close Modal via Close button
    modalClose.addEventListener('click', closeModal);

    // Close Modal by clicking outside content
    rsvpModal.addEventListener('click', (e) => {
        if (e.target === rsvpModal) {
            closeModal();
        }
    });

    function closeModal() {
        rsvpModal.classList.remove('show');
        document.body.style.overflow = ''; // Re-enable background scrolling
    }

    // Lightweight inline toast (no blocking alerts)
    const toastEl = document.getElementById('toast');
    let toastTimer = null;
    function showToast(message, isError = false, duration = 3600) {
        if (!toastEl) return;
        toastEl.textContent = message;
        toastEl.classList.toggle('error', isError);
        toastEl.classList.add('show');
        clearTimeout(toastTimer);
        toastTimer = setTimeout(() => toastEl.classList.remove('show'), duration);
    }

    // Submit RSVP to Supabase
    formRsvp.addEventListener('submit', async (e) => {
        e.preventDefault();

        const name = document.getElementById('rsvp-name').value.trim();
        const phone = document.getElementById('rsvp-phone').value.trim();
        const message = document.getElementById('rsvp-message').value.trim();
        const statusEl = document.querySelector('input[name="rsvp-status"]:checked');
        const confirmacion = statusEl ? statusEl.value === 'Si' : true;

        // Close the form immediately so it feels instant; save in the background
        closeModal();
        showToast('Guardando tu confirmación…', false, 8000);

        try {
            const client = await ensureSupabase();
            const { error } = await client
                .from('rsvp')
                .insert([
                    {
                        event_slug: 'joao-vitalia', // Identificador único para este evento
                        nombre: name,
                        numero: phone,
                        confirmacion: confirmacion,
                        mensaje: message
                    }
                ]);

            if (error) throw error;

            formRsvp.reset();
            markRsvpDone();
            showToast(confirmacion
                ? '¡Gracias! Te esperamos con mucho cariño. 🤍'
                : 'Gracias por avisarnos, te vamos a extrañar. 🤍');
        } catch (error) {
            console.error('Error al registrar RSVP en Supabase:', error);
            // Reopen the form (data is preserved) so the guest can retry
            openRsvpModal();
            showToast('No se pudo guardar. Revisa tu conexión e inténtalo de nuevo.', true, 4500);
        }
    });

    // ==========================================================================
    // SCROLL REVEAL (Intersection Observer)
    // ==========================================================================
    
    function initScrollReveal() {
        // Elements that fade-in and slide-up on scroll
        const revealElements = document.querySelectorAll('.reveal');
        
        const revealObserver = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('active');
                    observer.unobserve(entry.target); // Trigger only once
                }
            });
        }, {
            threshold: 0.1, // Trigger when 10% of the element is visible
            rootMargin: '0px 0px -40px 0px' // Adjust triggers to feel early
        });

        revealElements.forEach(element => {
            revealObserver.observe(element);
        });

        // Set sequence indexes for stagger timeline
        const timelineItems = document.querySelectorAll('.timeline-item');
        timelineItems.forEach((item, index) => {
            item.style.setProperty('--stagger-delay', index % 4);
        });
    }

    // ==========================================================================
    // SCROLL PROGRESS INDICATOR
    // ==========================================================================
    const scrollProgress = document.getElementById('scroll-progress');
    if (scrollProgress && !CSS.supports('animation-timeline', 'scroll()')) {
        let ticking = false;
        window.addEventListener('scroll', () => {
            if (!ticking) {
                window.requestAnimationFrame(() => {
                    const winScroll = document.body.scrollTop || document.documentElement.scrollTop;
                    const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
                    const scrolled = height > 0 ? (winScroll / height) : 0;
                    scrollProgress.style.transform = `scaleX(${scrolled})`;
                    ticking = false;
                });
                ticking = true;
            }
        }, { passive: true });
    }

    // Fallback in case user enters without dismissing the overlay (e.g. refresh after enter)
    // We initialize observer if screen is scrolled past top
    if (window.scrollY > 100) {
        initScrollReveal();
    }

    // Sticky Floating RSVP Button toggle
    const floatingRsvpBtn = document.getElementById('floating-rsvp-btn');
    const rsvpSection = document.getElementById('rsvp');
    
    if (floatingRsvpBtn) {
        floatingRsvpBtn.addEventListener('click', openRsvpModal);
        
        window.addEventListener('scroll', () => {
            if (isRsvpDone()) { floatingRsvpBtn.classList.remove('show'); return; }
            const scrollPos = window.scrollY || document.documentElement.scrollTop;

            // Show after 400px, but hide if we are near the bottom RSVP section
            const rsvpTop = rsvpSection ? rsvpSection.getBoundingClientRect().top + window.scrollY : 10000;
            const triggerPos = 400;
            const hidePos = rsvpTop - window.innerHeight + 100;

            if (scrollPos > triggerPos && scrollPos < hidePos) {
                floatingRsvpBtn.classList.add('show');
            } else {
                floatingRsvpBtn.classList.remove('show');
            }
        }, { passive: true });
    }
});
